name: deploy-book

# Only run this when a release is made
on:
  release:
    types: [created]

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install ".[dev]"

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html

