name: Publish worklab package to PyPI

# Only run this when a release is made
on:
  release:
    types: [created]

jobs:
  build-n-publish:
    name: Build and publish package
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install package
      run: >-
        python -m
        pip install
        ".[dev]"
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        .
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish package 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
